### ISSUE TITLE
API expansion

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#195]
See #149, #148.
TODO:
- [x] `parse_single` #187
- [x] `select_as_string` #187
- [ ] `select_as_json` Pending: #200
- [x] `insert_vec` #193
- [ ]  `insert_vec_as_string`
- [ ] `insert_csv` (Alternative) Resolve: #153
