### ISSUE TITLE
Support `Inline view` (FROM clause subquery)

### ISSUE THREAD

**Issue by devgony** [gluesql/gluesql#522]
### Currently GlueSQL supports subqueries at
- SELECT clause (Scala)
- WHERE clause (Subquery)
### But not yet
- FROM clause (Inline view)
### Examples
```SQL
CREATE TABLE Test (id INTEGER, name TEXT);
INSERT INTO Test VALUES (1, 'GLUE'), (2, 'SQL');
```
```SQL
SELECT * FROM (SELECT COUNT(*) cnt FROM Test);
```
should return
```SQL
cnt
---
  2
```
It looks like similar with issue: #152 and is related with #417.
### Todo
- [x] Add initial test cases at `test-suite/src/inline_view.rs`
- [x] Add `TableFactor::Derived {subquery, alias}` at `core/src/ast/query.rs`
- [x] Fix UnsupportedQueryTableFactor -> Return TableFactor::Derived at `core/src/translate/query.rs`
- [ ] Should we separate TableFactor to TableFactorEvaluate and TableFactorTranslate?
- [ ] Sth to do in plan?
- [ ] Impl if relation == Derived, select(subquery) in `select_with_label` at `core/src/executor/select/mod.rs`
