### ISSUE TITLE
Change the implementation of `*Into` to `*From`

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#619]
<https://doc.rust-lang.org/stable/std/convert/trait.Into.html>

One should avoid implementing [Into](https://doc.rust-lang.org/stable/std/convert/trait.Into.html) and implement [From](https://doc.rust-lang.org/stable/std/convert/trait.From.html) instead. Implementing [From](https://doc.rust-lang.org/stable/std/convert/trait.From.html) automatically provides one with an implementation of [Into](https://doc.rust-lang.org/stable/std/convert/trait.Into.html) thanks to the blanket implementation in the standard library.

**Comment by ever0de** [comment]
ex) https://github.com/gluesql/gluesql/blob/0aef013650dd10081d7af123f3b1db49e34d68bb/core/src/data/value/into.rs#L48

**Comment by nyeong** [comment]
## Tasks

Implementations to be changed might be:

### core/src/data/value/into.rs
- [ ] 49:`impl TryInto<bool> for &Value { ... }` 
- [ ] 116:`impl TryInto<bool> for Value { ... }` 
- [ ] 124:`impl TryInto<i8> for &Value { ... }` 
- [ ] 159:`impl TryInto<i8> for Value { ... }` 
- [ ] 167:`impl TryInto<i16> for Value { ... }` 
- [ ] 175:`impl TryInto<i16> for &Value { ... }` 
- [ ] 210:`impl TryInto<i32> for &Value { ... }` 
- [ ] 245:`impl TryInto<i32> for Value { ... }` 
- [ ] 253:`impl TryInto<i64> for &Value { ... }` 
- [ ] 288:`impl TryInto<i64> for Value { ... }` 
- [ ] 296:`impl TryInto<i128> for &Value { ... }` 
- [ ] 331:`impl TryInto<i128> for Value { ... }` 
- [ ] 339:`impl TryInto<f64> for &Value { ... }` 
- [ ] 374:`impl TryInto<f64> for Value { ... }` 
- [ ] 382:`impl TryInto<Decimal> for &Value { ... }` 
- [ ] 417:`impl TryInto<Decimal> for Value { ... }` 
- [ ] 425:`impl TryInto<NaiveDate> for &Value { ... }` 
- [ ] 438:`impl TryInto<NaiveTime> for &Value { ... }` 
- [ ] 450:`impl TryInto<NaiveDateTime> for &Value { ... }` 
- [ ] 463:`impl TryInto<Interval> for &Value { ... }` 
- [ ] 474:`impl TryInto<u128> for &Value { ... }` 

### core/src/executor/evaluate/evaluated.rs
- [ ] 29:`impl TryInto<Value> for Evaluated<'_> { ... }` 
- [ ] 61:`impl TryInto<bool> for Evaluated<'_> { ... }`

**Comment by nyeong** [comment]
Suggestion: After changes, no `TryInto` or `Into` traits remain in `data/value/into.rs`. I suggest replacing the file name with `data/value/from.rs`.

**Comment by ever0de** [comment]
> Suggestion: After changes, no `TryInto` or `Into` traits remain in `data/value/into.rs`. I suggest replacing the file name with `data/value/from.rs`.

Agree, `from.rs` is fine, but what about `convert` ?
like [std::convert](https://doc.rust-lang.org/stable/std/convert/index.html)

**Comment by nyeong** [comment]
`convert` sounds better. I'm working with that.

**Comment by ever0de** [comment]
> `convert` sounds better. I'm working with that.

oh i'll add you to the assignee, thanks
