### ISSUE TITLE
[AST Builder] Implement create_table statement

### ISSUE THREAD

**Issue by ding-young** [gluesql/gluesql#713]
## Description
Implement ast_builder `create_table` statement 

## Tasks
- [ ] implement basic create table statement  
- [ ] block invalid column options (ex. NULL NOT NULL)
- [ ] implement create table as statement (with subquery) 

## Issue
referred #614 

## Description
Following tests should be passed. 
```rust
    #[test]
    fn create_table() {
        let actual = table("Foo")
                .create_table()
                .set_col(col("id"), "int", null())
                .set_col(col("num"), "int")
                .set_col(col("name"), "text")
                .build();
        let expected = "CREATE TABLE Foo (id INTEGER NULL, num INTEGER, name TEXT)";

        let actual = table("Foo")
                .create_table_if_not_exists()
                .set_col(col("id"), "uuid", unique())
                .build();
        let expected = "CREATE TABLE IF NOT EXISTS Foo (id UUID UNIQUE)";

        test(actual, expected);
    }
```

**Comment by ever0de** [comment]
It seems to be a problem solved in #784. Can I close it?

**Comment by pythonbrad** [comment]
Hi, this issue has been solved?

**Comment by ever0de** [comment]
> Hi, this issue has been solved?

There doesn't seem to be a subquery implementation yet.

**Comment by ever0de** [comment]
> Hi, this issue has been solved?

There doesn't seem to be a subquery implementation yet.

**Comment by ding-young** [comment]
> Hi, this issue has been solved?

Hi, ast builder for basic create table statement has been implemented, but you can still work on supporting ast builder for create table with subquery
