### ISSUE TITLE
[AST] Implement Geometic Point Type and Geometric fucntion in AST

### ISSUE THREAD

**Issue by seonghun-dev** [gluesql/gluesql#989]
# Description
We want to support the following functions that can be used to analyze geographic data, identify spatial relationships between terrain features, and construct or manipulate GEOGRAPHY.

> ### Spaital Standard Document
> spatial data types and functions define standards in the Open Geospatial Consortium
> All data types and functions are based on the this documents
> http://portal.opengeospatial.org/files/?artifact_id=25354

## Point

`POINT`
The position of a point in the coordinate space
Points are the fundamental two-dimensional building block for geometric types

### Example
DataType `POINT`

``` sql
POINT(10 20)
```

Function `ST_POINT`

Return the Point

``` sql
SELECT ST_POINT(POINT(15 20));
```

Function `ST_X`

Return the X-coordinate of point

``` sql
SELECT ST_X(POINT(15 20));
```

Function `ST_Y`

Return the Y-coordinate of point
``` sql
SELECT ST_Y(POINT(15 20));
```

# Task
- [ ] Add `POINT` DataType
- [ ] Add `ST_POINT` Fucntion
- [ ] Add `ST_X` Fucntion
- [ ] Add `ST_Y` Fucntion

The following tests should be passed:

``` rust
test_case!(point, async move {

    let test_cases = [
        ("CREATE TABLE POINT (point_field POINT)", Ok(Payload::Create)),
        (
            r#"INSERT INTO POINT VALUES(15 20);"#,
            Ok(Payload::Insert(2))
        ),
        (
             r#"SELECT point_field AS point_field FROM POINT;"#,
            Ok(select!(
                point_field
                Point;
                Point(15 20);
            ))
        ),
	(
		r#"SELECT ST_POINT(POINT(15 20));"#,
           Ok(select!(
                column1
                Point;
                Point(15 20);
		))
	),
	(
	     r#"SELECT ST_X(POINT(15 20))"#,
            Ok(select!(
                column1
                F64;
                f64::from(15);
            ))
	),
	(
	     r#"SELECT ST_Y(POINT(15 20))"#,
            Ok(select!(
                column1
                F64;
                f64::from(20);
            ))
	)
    ];

    for (sql, expected) in test_cases {
        test!(expected, sql);
    }
});
```

### Reference
http://portal.opengeospatial.org/files/?artifact_id=25354
http://postgis.net/workshops/postgis-intro/geometries.html
https://dev.mysql.com/doc/refman/5.7/en/gis-data-formats.html
https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions
https://redis.com/redis-best-practices/indexing-patterns/geospatial/
https://learn.microsoft.com/en-us/sql/t-sql/spatial-geometry/spatial-types-geometry-transact-sql?view=sql-server-ver16
